language: python

matrix:
  include:
    # - os: linux
    #   dist: bionic
    - os: windows
      language: shell

before_install:
  - choco install python
  - echo $TRAVIS_OS_NAME;
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "Windows build before_install";
        # wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi
        # choco install python-x86_32 --version=3.4.2
    #     choco install python --version=3.4.4;
    #     python -m pip install --upgrade pip;
    #     pip install pyinstaller;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Linux build before_install";
    # elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    #     echo "OS X build";
    else echo "No match in before_install";
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      # .\\build.cmd;
      echo "Windows script";
      # pyinstaller --onefile --noconsole sandbox\__main__.py --name sandbox
      # sleep 1  # Allow pyinstaller to finish writing to stdout
      # dist/sandbox.exe
      # echo "Did something print?";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Linux script";
    #   # docker exec -t xenial /build/setup.sh;
    #   # docker exec -t xenial /build/build.sh;
    # elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    #   git submodule update --init --recursive;
    #   ./setup.sh;
    #   ./build.sh;
    fi
