env:
  global:
    - PY34PATH=/c/Python34:/c/Python34/Scripts:/c/tools/python-x86_32:/c/tools/python-x86_32/Scripts
# chocolatey installs
#  * choco install python-x86_32 --version=3.4.2 to '/c/tools/python-x86_32'
#  * choco install python --version=3.4.4        to '/c/Python34'

language: python

jobs:
  allow_failures:
    - env: ALLOW_FAILURES=true
  include:
    # - os: linux
    #   dist: bionic
    - os: windows
      language: shell
      env: PATH=$PY34PATH:$PATH

before_install:
  # No $TRAVIS_OS_NAME here
  - echo "Running a before_install"

# No comments in '-' section allowed
# wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi
# 
script:
  - echo "Running script on $TRAVIS_OS_NAME platform"
  - pwd
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "Windows condition";
        .\\hello.bat;
        choco install python-x86_32 --version=3.4.2;
        python -m pip install --upgrade pip;
        pip install pyinstaller;
        pyinstaller --onefile --noconsole sandbox/__main__.py --name sandbox;
        sleep 1;
        dist/sandbox.exe;
        echo "End of windows condition";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Linux condition";
        ./hello.sh;
        python -m sandbox;
        echo "End of linux condition";
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "OS X condition";
    else echo "Unknown OS";
    fi
