env:
  global:
    - PY34PATH=/c/Python34:/c/Python34/Scripts:/c/tools/python-x86_32:/c/tools/python-x86_32/Scripts

# wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi

# chocolatey installs
#  * choco install python-x86_32 --version=3.4.2 to '/c/tools/python-x86_32'
#  * choco install python --version=3.4.4        to '/c/Python34'

# mingw already in PATH, it will brake python/pip search
# cmd.exe //c RefreshEnv.cmd;

language: python

jobs:
  allow_failures:
    - env: ALLOW_FAILURES=true
  include:
    - os: linux
      dist: bionic
    - os: windows
      language: shell
      env: PATH=$PY34PATH:$PATH
    - os: osx
      language: shell
#       python: "3.4"

before_install:
  # No $TRAVIS_OS_NAME here
  - echo "Running a before_install"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

# install:
#   - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then   mac-build/install.sh ; fi

# No comments in '-' section allowed
script:
  - echo "Running script on $TRAVIS_OS_NAME platform"
  - pwd
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "Windows condition";
        .\\hello.bat;
        choco install python-x86_32 --version=3.4.2;
        python -m pip install --upgrade pip;
        pip install pyinstaller;
        pyinstaller --onefile --noconsole sandbox/__main__.py --name sandbox;
        sleep 1;
        dist/sandbox.exe;
        echo "End of windows condition";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Linux condition";
        ./hello.sh;
        python -m sandbox;
        echo "End of linux condition";
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "OS X condition";
        python3 --version;
    else echo "Unknown OS";
    fi

# before_deploy:
#   - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then cp mac-build/dist/file.dmg /Users/travis/file.dmg ; fi

# deploy:
#   # see https://docs.travis-ci.com/user/deployment/releases/
#   - provider: releases
#     api_key:
#       secure: 
#     file: /Users/travis/file.dmg
#     file: dist/sandbox.exe
#     skip_cleanup: true
#     draft: true
#     on:
#       tags: true
#       condition:  "\"$TRAVIS_OS_NAME\" == \"osx\""
#       repo: radioxoma/sandbox

# after_deploy:
#   - ./after_deploy_1.sh
#   - ./after_deploy_2.sh
