# Windows
# wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi
# chocolatey installs:
#  * choco install python-x86_32 --version=3.4.2 to '/c/tools/python-x86_32'
#  * choco install python --version=3.4.4        to '/c/Python34'
# mingw already in PATH, it will brake python/pip search
# cmd.exe //c RefreshEnv.cmd;

language: python

jobs:
  include:
  - os: linux
    dist: bionic
  - os: windows
    language: shell
    env: PATH=/c/tools/python-x86_32:/c/tools/python-x86_32/Scripts:$PATH
    install:
    # I need python3.4 for compatibility with Windows XP
    # pip 19.2 drops support for python 3.4 (despite 19.3.1 been working fine)
    # Key '--user' is mandatory outside virtualenv 'language: python'
    - choco install python-x86_32 --version=3.4.3.20150501
    - python -m pip install --user --upgrade pip==19.1.1
    - python -m pip install --user pyinstaller  # Avoid old binary in PATH
  - os: osx
    language: shell
    install:
    # Travis has python3 preinstalled with Brew to `/usr/local/bin/python3`
    # - brew upgrade python
    - brew install tree
    - alias python=/usr/local/bin/python3
    - python -m pip install --user --upgrade pip
    - python -m pip install --user pyinstaller

# These scripts should be able to build project on Travis and locally
script:
  - python --version
  - python -m unittest
  - echo "Running script on $TRAVIS_OS_NAME platform"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "Windows script start";
        .\\build.bat;
        echo "Windows script end";
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "OS X script start";
        ./build_osx.sh;
        echo "OS X script end";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Linux script start";
        echo "Linux script end";
    fi

deploy:
  provider: releases
  token:
    secure: twyg+DsFZN2zAlq0S4jEcl8AAFpfbGj4sFswHgNLaCm0kshpL42oxL531Ubz/QuqtCPsklvtchkAumGPzE9Ec2mANQGOtDHAgeC9Uhjls2cwCtrlQ8O4saOpoXTYKjw/RMwy4HaA3YRppvFaHjSDdWx3zeWt6w1KtfLw1ZlvQnIPt/NusJr6lkKd57+Ct2MpgZiRxLo+r2x8Y/VutlgAmPozc7KlILxcaUnpyNqKAsjmNzzLe5WAKEV8rzCpvhPc9DiUdql3zGi4/V6FMmSeKmJGTmls4fdGUYobedljgXpAbMtIeqquxkxbCOIhY/bEUoSipkjwVyVFYgmOPay9VzJDo/5DicxIjvn55yQJ9rSc3gvdlbirHMXNANjLNU167h2jl1cwvaq3hSF8U3zfJ4pB5PKv68V4j0RSdYg64shWimpqJUcFJAzPQav5OiO9nwt+RF+TDG5DoLKf6GvjJKCr6Qedf3oQ7Vx499ByKUKA6Qqn8emcbXZ3NOw7DJAAkY/qcWs07zPsdyrO4raghis3b1gw36sB7ia8A404SWdagz+/yGvhG+J38kLwSEWbUqGFHaZKdJEniqnkhblvcpuDV5hYbUJZsawfvEmOPKqBYT+Cd13cw5xDFnBSUi5d7MmG3YubgpZrtMlf3N7zsPpwZM4MOoZvgTy9sOoQqzU=
  file_glob: true
  file: "dist/sandbox.*"
#  file: "${RELEASE_FILE}"
  skip_cleanup: true
  draft: true
#  prerelease: true
  overwrite: true
  name: "Automatical dev build by Travis CI"
#  body: "Body text"
  on:
    repo: radioxoma/sandbox
    tags: true
    condition: "\"$TRAVIS_OS_NAME\" != \"linux\""
