language: python

jobs:
  allow_failures:
    - env: ALLOW_FAILURES=true
  include:
    - os: linux
      dist: bionic
    - os: windows
      language: shell

before_install:
  # No $TRAVIS_OS_NAME here
  - echo "Running a before_install"

script:
  - echo "Running script on $TRAVIS_OS_NAME platform"
  - pwd
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "Windows condition";
        .\\hello.bat;
        # wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi
        # choco install python-x86_32 --version=3.4.2;
        # choco install python --version=3.4.4;
        # python -m pip install --upgrade pip;
        # pip install pyinstaller;

        # pyinstaller --onefile --noconsole sandbox\__main__.py --name sandbox
        # sleep 1  # Allow pyinstaller to finish writing to stdout
        # dist/sandbox.exe
        echo "End of windows condition";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Linux condition";
        ./hello.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "OS X condition";
    else echo "Unknown OS";
    fi
  - echo "End"
