language: python

jobs:
  allow_failures:
    - env: ALLOW_FAILURES=true
  include:
    - os: linux
      dist: bionic
    - os: windows
      language: shell

before_install:
  # No $TRAVIS_OS_NAME here
  - echo "Im a before_install"

script:
  - echo "Im a script running on $TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "Windows condition";
        .\\hello.bat;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo "Linux condition";
        sh ./hello.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "OS X condition";
    else echo "Unknown OS";
    fi
  - pwd
  - ls -la
  - echo "End"
