name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:  # Latest Windows 7 compatible binary release from python.org
          python-version: "3.8.10"
          architecture: x86
      - run: python -m unittest -v

      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - run: .\build.bat

      - uses: actions/upload-artifact@v3
        with:
          path: "dist/sandbox*"  # Both *.exe and *.dmg
          if-no-files-found: error

      - uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/sandbox*"  # Both *.exe and *.dmg
          fail_on_unmatched_files: true
